/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
// SEN Manual change for ITM START
#include<stdio.h>
int main(void)
{
	// SEN Manual change for ITM START
	printf("Hello using ITM\n");

	for(;;);
}
